'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

two_last_fibonacci = [1,2]
sum_of_even_fibonaccis = 2

while True:
    next_fibonacci = two_last_fibonacci[0] + two_last_fibonacci[1]
    if next_fibonacci > 4000000:
        break

    fibonacci_is_even = next_fibonacci % 2 == 0    
    if (fibonacci_is_even):
        sum_of_even_fibonaccis += next_fibonacci

    two_last_fibonacci[0] = two_last_fibonacci[1] 
    two_last_fibonacci[1] = next_fibonacci

#result
print(sum_of_even_fibonaccis)

  

